// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgA54EnVQJl8quCI_44yVCvtBwOw1UH3g',
    appId: '1:768935755165:web:250e6e361096fcb6da0374',
    messagingSenderId: '768935755165',
    projectId: 'les-vagues',
    authDomain: 'les-vagues.firebaseapp.com',
    storageBucket: 'les-vagues.firebasestorage.app',
    measurementId: 'G-57XBKW4DX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTIWN_6U82eesHSblgUk1a2EHGPJI-fGA',
    appId: '1:768935755165:android:905df6db014f8923da0374',
    messagingSenderId: '768935755165',
    projectId: 'les-vagues',
    storageBucket: 'les-vagues.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgA54EnVQJl8quCI_44yVCvtBwOw1UH3g',
    appId: '1:768935755165:web:4ae8b211a648d50ada0374',
    messagingSenderId: '768935755165',
    projectId: 'les-vagues',
    authDomain: 'les-vagues.firebaseapp.com',
    storageBucket: 'les-vagues.firebasestorage.app',
    measurementId: 'G-S2529SVFM3',
  );
}
